<?php
/**
 * @file
 * Provide the Trackback protocol to the Linkback module.
 */


/**
 * Implementation of hook_linkback_handler().
 */
function linkback_trackback_linkback_handler() {
  return array(
    'protocol' => t('Trackback'),
  );
}

/**
 * Implements hook_menu().
 */
function linkback_trackback_menu() {
  // END-POINT for trackback registration. Not for humans!
  $items['node/%node/trackback'] = array(
    'title' => 'Trackbacks',
    'page callback' => 'linkback_receive_trackback',
    'page arguments' => array(1),
    // This URL is accessible according to the node's visibility to ANONYMOUS
    // users and whether 'Receive linkbacks' is allowed on the node.
    'access callback' => 'linkback_trackback_node_access',
    // The use of drupal_anonymous_user() passes the anonymous user object to
    // the access callback (and the object itself is cached in the menu
    // registry, so drupal_anonymous_user() is not called for each request to
    // this URL).
    'access arguments' => array(1, drupal_anonymous_user()),
    'file' => 'linkback.admin.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}


/**
 * Implementation of hook_node_view().
 *
 * The trackbacl protocol is handled by a helper function, which may be
 * replaced by rdf-integration at some point.
 */
function linkback_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full' && linkback_node_allows_linkback($node, 'receive')) {
    _linkback_add_trackback_receive($node);
  }
}


/**
 * Add the RDF which allows trackbacks to be tracked.
 *
 * @TODO: investigate integrating this with the RDF module.
 */
function _linkback_add_trackback_receive($node) {
  // Canonical URL to the node.
  $url = url('node/'. $node->nid, array('absolute' => TRUE));
  // Trackback end-point for this specific node.
  $tb_url = _linkback_get_trackback_endpoint($node);

  $rdf_text = "\n<!--\n";
  $rdf_text .= '<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:trackback="http://madskills.com/public/xml/rss/module/trackback/">'."\n";
  $rdf_text .= '<rdf:Description rdf:about="'. $url .'" dc:identifier="'. $url .'" dc:title="'. strtr(check_plain($node->title), array('--' => '&mdash;')) .'" trackback:ping="'. $tb_url .'" />'."\n";
  $rdf_text .= '</rdf:RDF>';
  $rdf_text .= "\n-->\n";

  $node->content['trackback'] = array(
    '#markup' => $rdf_text,
  );
}


/**
 * Menu callback to register a trackback.
 */
function linkback_receive_trackback($node) {
  
}


/**
 * The trackback endpoint for each node is at:
 * node/%node/trackback
 */
function _linkback_get_trackback_endpoint($node) {
  return url("node/{$node->nid}/trackback", array('absolute' => TRUE));
}

