<?php
/**
 * @file
 * Provide a dummy handler to test the Vinculum module.
 */

/**
 * Implements hook_vinculum_handler().
 */
function vinculum_dummy_handler_vinculum_handler() {
  return array(
    'protocol' => t('Dummy handler'),
  );
}


/**
 * Implements hook_vinculum_send().
 *
 * This handler always reports success.
 */
function vinculum_dummy_handler_vinculum_send($target, $source, $node) {
  return TRUE;
}
