<?php
/**
 * @file
 * Integrates with core trigger module to fire events when vinculums are sent
 * or received.
 *
 * Provides:
 * - Registration of trigger actions.
 * - Fires actions when vinculums are send/received.
 * - Default actions to create comments, etc.
 */

/**
 * Implements hook_trigger_info().
 */
function vinculum_trigger_trigger_info() {
  return array(
    'vinculum' => array(
      'vinculum_receive' => array(
        'label' => t('When a new vinculum is received'),
      ),
    ),
  );
}



/**
 * Implements hook_action_info().
 */
function vinculum_trigger_action_info() {
  return array(
    'vinculum_create_comment_action' => array(
      'type' => 'vinculum',
      'label' => t('Create comment'),
      // Available configuration for the new comments:
      // - Should comment be published?
      'configurable' => TRUE,
      'triggers' => array('vinculum_receive'),
    ),
  );
}

/**
 * Configuration form for the vinculum_create_comment_action action.
 */
function vinculum_create_comment_action_form($context) {
  $form['status'] = array(
    '#title' => t('Published'),
    '#type' => 'checkbox',
    '#default_value' => isset($context['status']) ? $context['status'] : TRUE,
  );

  return $form;
}

/**
 * Configuration form submit handler for the vinculum_create_comment_action
 * action.
 */
function vinculum_create_comment_action__submit($form, $form_state) {
  return (bool) array_filter($form_state['values']['status']);
}



/**
 * Implements hook_vinculum_received_action().
 */
function vinculum_trigger_vinculum_received_action($record) {
  // Fire the vinculum_receive trigger when a vinculum is sent.
  drupal_set_message('DEBUG: the vinculum hook is fired.');
  watchdog('lb', 'vinculum hook fired.');
}

